name: Create CV in PDF
on: [push]
jobs:
  buildMD:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: mkdir output
    - name: Convert md to pdf
      uses: docker://pandoc/latex:latest
      with: 
        args: "--standalone --output=output/cv_md.pdf cv.md"
    - uses: actions/upload-artifact@master
      with:
        path: output
        name: cv_md.pdf
  buildTexV1:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: mkdir output   
    - name: Convert tex_v1 to pdf
      uses: xu-cheng/latex-action@master
      with:
        root_file: cv.tex
        working_directory: tex_v1/src
        compiler: xelatex
    - run: pwd
    - run: ls
    - run: cp src/cv.pdf output/cv_tex_v1.pdf
    - uses: actions/upload-artifact@master
      with:
        path: output
        name: cv_tex_v1.pdf
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [buildMD, buildTexV1]
    runs-on: ubuntu-18.04
    steps:
    - name: Get md
      uses: actions/download-artifact@master
      with:
        name: cv_md.pdf
        path: .
    - name: Get tex v1
      uses: actions/download-artifact@master
      with:
        name: cv_tex_v1.pdf
        path: .
    - name: Prepare final
      run: cp cv_tex_v1.pdf CV_Rafael_Mukhametdzhanov.pdf
    - name: Save
      uses: softprops/action-gh-release@v0.1.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          CV_Rafael_Mukhametdzhanov.pdf
          cv_md.pdf
          cv_tex_v1.pdf
